# Exception Handling 2

<br>

---

<br>

## `try ~ finally` 구문

```c#
using System;

class Program
{
	static void Main()
    {
        try
        {
            throw new Exception();
        }
        catch (Exception e)
        {
            Console.WriteLine("catch");
        }
        finally
        {
            Console.WriteLine("finally");
        }
    }
}
```

<br>

#### catch vs finally

* **`catch`**
  * try 블록 안에서 **예외가 발생시 실행**
* **`finally`**
  * try 블록을 **벗어날 때 항상 실행**

<br>

#### 실행 순서

* 예외가 발생하면
  * try → catch → finally
* 예외가 발생하지 않으면
  * try → finally

<br>

#### 만약에...

* catch 문을 주석처리하면?
  * 프로그램이 예외로 종료하게 되더라도
  * finally 문은 실행됨

* try 문에 `return;`이 있다면?
  * finally 문은 실행됨
* try 문이 실행되기 전에 `return;`이 있다면?
  * try 문이 실행되지 않았기 때문에 
  * finally 문 실행 안됨

<br>

#### 결론

* try 문에 들어갔다가 나갔을 때는 반드시 finally 문이 실행됨

* 따라서 **자원 반납하는 용도**로 사용하면 좋음

<br>

---

<br>

## 자원 관리

<br>

#### C# 에서의 자원 관리

* `new`로 생성한 일반적인 객체들
  * Garbage Collector에 의해 자동으로 수집됨
  * 명시적으로 자원을 해지 할 필요 없음
* **파일, 네트워크** 등의 자원을 관리하는 객체
  * **`Dispose()` 메소드를 호출해서 명시적으로 자원을 해지**해야 함

→ 자세한 내용은 **Garbage Collector**와 **Dispose 패턴** 참고

<br>

#### `finally` 를 사용한 자원 관리

```c#
using System;
using System.IO;

class Program
{
	static void Main()
    {
        FileStream fs = null;
        
        try
        {
        	fs = new FileStream("a.txt", FileMode.CreateNew);
        
        	// ...
        }
        catch(Exception e)
        {
            
        }
        finally
        {
            // try 문을 빠져나오면 항상 실행되므로 가장 안전하게 자원관리 하는 방법
            if (fs != null)
            	fs.Dispose();
        }
    }
}
```

<br>

#### `using` 을 사용한 자원 관리

```c#
using System;
using System.IO;

class Program
{
	static void Main()
    {
        using( FileStream fs = new FileStream("a.txt", FileMode.CreateNew) )
        {
        	try
            {
                
            }
            catch( Exception e)
            {
                
            }
        }
    }
}
```

* finally를 사용한 자원관리 방법이 많이 사용되다보니 등장!!
* 컴파일되면 내부적으로 `try ~ finally` 문으로 변환됨
  * 위의 "`finally` 를 사용한 자원 관리" 코드와 같이 변환됨

* 자원관리 이외에 예외처리 해야하는 부분이 있다면 
  * 중첩  `try ~ catch ~ finally` 문 사용하면 됨!!